version: '3.7'

services:
  'rundeck':
    hostname: localhost
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUNDECK_VERSION=2.11.14
    container_name: rundeck-arm
    image: malibukoko/rundeck_arm:v2.2
    restart: unless-stopped
    expose:
      - 4440
      - 4443
    ports:
      - 4440:4440
      - 4443:4443
    volumes:
      - /opt/rundeck/etc:/opt/rundeck/etc:rw
      - /opt/rundeck/var:/opt/rundeck/var:rw
      - /opt/rundeck/projects:/opt/rundeck/projects:rw
      - /opt/rundeck/server/config:/opt/rundeck/server/config:rw
      - /opt/rundeck/server/data:/opt/rundeck/server/data:rw
      - /opt/rundeck/server/logs:/opt/rundeck/server/logs:rw
      - /opt/rundeck/tools:/opt/rundeck/tools:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
