version: '3.7'

services:
  'rundeck':
    hostname: localhost
    build:
      context: .
      dockerfile: Dockerfile
      args:
        #- BASE_IMAGE=scaleway/java:armhf-latest
        - BASE_IMAGE=arm64v8/openjdk:11-jdk-slim
        - RUNDECK_VERSION=2.11.14
    container_name: rundeck-arm
    entrypoint: tail -f /dev/null
    image: malibukoko/rundeck_arm:v2.2
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 500M
        reservations:
          cpus: '0.5'
          memory: 250M
    restart: unless-stopped
    expose:
      - 4440
      - 4443
    ports:
      - 4440:4440
      - 4443:4443
    volumes:
      - /opt/rundeck/etc:/opt/rundeck/etc:rw
      - /opt/rundeck/var:/opt/rundeck/var:rw
      - /opt/rundeck/projects:/opt/rundeck/projects:rw
      - /opt/rundeck/server/config:/opt/rundeck/server/config:rw
      - /opt/rundeck/server/data:/opt/rundeck/server/data:rw
      - /opt/rundeck/server/logs:/opt/rundeck/server/logs:rw
      - /opt/rundeck/tools:/opt/rundeck/tools:rw
    logging:
      driver: json-file
      options:
        max-size: 10m
